version: 1
accounts:
  - name: alice
    coins: ["200000000uluna"]
  - name: bob
    coins: ["100000000uluna"]
validators:
  - name: alice
    bonded: "100000000uluna"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000uluna"]
